"""Legacy import compatibility: pure re-exports; implementation lives in the adapter."""
from legacy_documenter.adapters.vbnet_webforms_oracle.extractors.database_extractor import (
    TYPE_RE,
    END_TYPE_RE,
    METHOD_RE,
    END_METHOD_RE,
    VAR_RE,
    STRING_ASSIGN_RE,
    FIELD_RE,
    PARAM_RE,
    NEW_ASSIGN_RE,
    COMMAND_NEW_RE,
    ADAPTER_NEW_RE,
    COMMAND_TEXT_RE,
    COMMAND_TYPE_RE,
    EXECUTE_RE,
    FILL_RE,
    PARAM_ADD_RE,
    ORACLE_PARAM_RE,
    DIRECTION_RE,
    WRAPPER_EXEC_RE,
    TRANSACTION_RE,
    CONNECTION_NAME_RE,
    DatabaseExtractor,
 )
